sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
      - master
      - /^greenkeeper/.*$/
notifications:
  email: true
node_js:
  - 6.1
  - 6
  - 5.6.0
  - 4.3.0
before_install:
  - npm i -g preact-cli
before_script:
  - npm prune
script:
  - npm run test
install: npm run build